services:
  db:
    build:
      context: ./docker/postgres
    container_name: postgres_age
    restart: unless-stopped
    command: >
      postgres
      -c shared_preload_libraries=age
      -c search_path=ag_catalog,"$$user",public
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=multimodel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-net

volumes:
  postgres-data:
    driver: local

networks:
  monitoring-net:
    driver: bridge
